Patch 1
shigobu/SAPIForVOICEVOX pull request #56
Opened 2022-04-03 01:30 UTC by Co-Jirou

2022-04-03 01:41 UTC, Co-Jirou commented
VoiceVoxConnectionException発生の時、エラー音声がセットされないです。
他の例外も、同じ懸念がありましたので、修正案です。
よろしくお願いいたします。

2022-04-03 09:44 UTC, shigobu commented
プルリクエストありがとうございます。
確かにその通りです。

一点、{}が重複していてビルドが通らないところがあるので、修正してください。

2022-04-03 09:45 UTC, shigobu requested changes

2022-04-03 09:45 UTC, shigobu commented on SAPIForVOICEVOX/Exception/VoiceVoxConnectionException.cs
> +        public VoiceVoxConnectionException(Exception innerException) : base(message, innerException) { }
この行の最後のカッコが重複しています。
修正をお願いします。

2022-04-04 11:29 UTC, Co-Jirou commented
大変失礼いたしました。
カッコ重複修正しました。

2022-04-04 11:39 UTC, shigobu approved these changes

2022-04-04 11:40 UTC, shigobu commented
LGTM！
マージします。

2022-04-04 11:40 UTC, merged